### PR TITLE
Change ln/log

### PR DESCRIPTION
**Pull request by Schwertspize**
Shouldn't do clicking on "log" the logarithm and "ln" the natural logarithm?

### CODE REVIEW

**Comment by pierremtb** [comment]
I don't know, probably because of my country. In french, ln is the "opposite" of exp, so ln(exp(x))=x. And log(10^x)=x. Is it different for you ?

**Comment by Schwertspize** [comment]
the standard log is log10 where, as you said, log(10^x)=x. I think, with ln it's vice versa, but what I've ment is that in the script there were (simplified) 
ln=log(...) 
log=ln(...) 
I just wanted to change it to
ln=ln(...)
log=log(...)

**Comment by pierremtb** [comment]
Okay. But if we do that, log(10^x) will be understood as ln(10^x), which is different from x.

**Comment by Schwertspize** [comment]
that's it.... I would say, just open the app and try it out... I can't, so I just said, the source code confused me.... some have to try out if that's now right. if so, then please comment that in the code, if not, please merge this pull request.... 
log(10^x) should be x

**Comment by pierremtb** [comment]
For now I didn't add log button, because I got no space, but I will think of a multi-log button, with a dropdown or sth like that. 
Just tried : ln(exp(2))=2
log() isn't working for now though…

**Pull request closed without merging**
